UTILS:=cat cp df ln ls mkdir mv realpath rm rmdir basename chfn colrm column cut diff dirname env expand fuser look lslogins lsof man paste patch pathchk printenv ps rev tail tr uname unexpand whatis whoami du file findmnt finger getent grep groups head hostid hostname id last login lsblk mountpoint namei newgrp readlink stat touch wc who
CTX:=$(UTILS)

INC_PATH+=$(R_ROOT)/usr/include $(R_ROOT)/usr/src/lib $(R_ROOT)/usr/src/sys/sys

include ../common.mk
