M:=istru
H:=$M
D:=
CTX:=$D $H
include ../common.mk

try1: $(ETC)/$M.conf
	$(TOC) -c $< runx -m libu '{"ud":{"name":"","ufs":"1","fd":"0","bsize":"124","sblock":"4","si":"6","inoblock":"18","inomin":"0","inomax":"0","dp":"0","fs":{"sblkno":"4","cblkno":"6","iblkno":"18","dblkno":"82","ncg":"4","bsize":"124","maxcontig":"16","maxbpg":"250","fsbtodb":"8","id":"514","sbsize":"31","cssize":"5","cgsize":"31","inosize":"20","desize":"7","inopb":"6","ipg":"96","cs":{"ndir":"0","nbfree":"918","nifree":"384"},"flags":"1","fs_fsmnt":"0","volname":"0","time":"1680697326","size":"1000","dsize":"918","magic":"17222"},"cg":{"g":{"cgx":"0","cs":{"ndir":"0","nbfree":"168","nifree":"96"},"ndblk":"0","iusedoff":"14","freeoff":"10","niblk":"18","rotor":"0","irotor":"0","nextfreeoff":"82","initediblk":"0","unrefs":"0","space":"0","magic":"17223"},"nino":"0","nblk":"82","inobmp":"0","bbmp":"4835703278458516698824703"},"ccg":"0","lcg":"0","error":"","sblockloc":"4","lookupflags":"0","mine":"0"},"n":1}'