pragma ton-solidity >= 0.60.0;
library libmime_message {

    uint8 constant MESSAGE_CPIM 	        = 1;   // [RFC3862]
    uint8 constant MESSAGE_delivery_status 	= 2;   // [RFC1894]
    uint8 constant MESSAGE_disposition_notification = 3;   // [RFC8098]
    uint8 constant MESSAGE_example 	 	    = 4;   // [RFC4735]
    uint8 constant MESSAGE_external_body    = 5;   // [RFC2045][RFC2046]
    uint8 constant MESSAGE_feedback_report 	= 6;   // [RFC5965]
    uint8 constant MESSAGE_global 	 	    = 7;   // [RFC6532]
    uint8 constant MESSAGE_global_delivery_status = 8;   // [RFC6533]
    uint8 constant MESSAGE_global_disposition_notification = 9;   // [RFC6533]
    uint8 constant MESSAGE_global_headers 	= 10;  // [RFC6533]
    uint8 constant MESSAGE_http 	     	= 11;  // [RFC-19]
    uint8 constant MESSAGE_imdn_xml 	 	= 12;  // [RFC5438]
    uint8 constant MESSAGE_news             = 13;  // (OBSOLETED by [RFC5537])[RFC5537][Henry_Spencer]
    uint8 constant MESSAGE_partial 	        = 14;  // [RFC2045][RFC2046]
    uint8 constant MESSAGE_rfc822 	        = 15;  // [RFC2045][RFC2046]
    uint8 constant MESSAGE_s_http           = 16;  // (OBSOLETE)[RFC2660]
    uint8 constant MESSAGE_sip 	     	    = 17;  // [RFC3261]
    uint8 constant MESSAGE_sipfrag 	 	    = 18;  // [RFC3420]
    uint8 constant MESSAGE_tracking_status 	= 19;  // [RFC3886]
    uint8 constant MESSAGE_vnd_si_simp      = 20;  // (OBSOLETED by request) [Nicholas_Parks_Young]
    uint8 constant MESSAGE_vnd_wfa_wsc 	 	= 21;  // [Mick_Conley]
}