TOOLS:=fsck mount reboot umount groupadd groupdel groupmod useradd userdel usermod dumpe2fs mke2fs mkfs tfs tmpfs uma_startup umm vmm vnp tucred tfiledesc subr_syscall subr_ucred subr_fdt subr_fattr subr_io subr_signal subr_proc subr_nl
CTX:=$(TOOLS)
INC_PATH+=../../usr/include ../../usr/src/lib ../../usr/src/sys/sys
include ../common.mk
